-- MySQL Script generated by MySQL Workbench
-- Thu Jun 15 22:43:41 2023
-- Model: airport_model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
DROP SCHEMA airport;
CREATE SCHEMA airport;
USE airport;

-- -----------------------------------------------------
-- Table airlines
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS airlines (
  id INT UNSIGNED NOT NULL,
  name VARCHAR(45) NOT NULL,
  code VARCHAR(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX code_UNIQUE (code ASC),
  UNIQUE INDEX id_UNIQUE (id ASC) 
);


-- -----------------------------------------------------
-- Table airplane_types
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS airplane_types (
  id INT UNSIGNED NOT NULL,
  brand VARCHAR(45) NOT NULL,
  model VARCHAR(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) 
);


-- -----------------------------------------------------
-- Table airplanes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS airplanes (
  id INT UNSIGNED NOT NULL,
  airline_id INT UNSIGNED NOT NULL,
  type_id INT UNSIGNED NOT NULL,
  capacity SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  INDEX airline_id (airline_id ASC),
  INDEX type_id (type_id ASC),
  CONSTRAINT FK1_airplanes
    FOREIGN KEY (airline_id)
    REFERENCES airlines (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK2_airplanes
    FOREIGN KEY (type_id)
    REFERENCES airplane_types (id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);


-- -----------------------------------------------------
-- Table countries
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS countries (
  id INT UNSIGNED NOT NULL,
  code VARCHAR(3) NOT NULL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) ,
  UNIQUE INDEX code_UNIQUE (code ASC) 
);


-- -----------------------------------------------------
-- Table airports
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS airports (
  id INT UNSIGNED NOT NULL,
  code VARCHAR(3) NOT NULL,
  name VARCHAR(45) NOT NULL,
  country INT UNSIGNED NOT NULL,
  longitude DECIMAL(6,2) NOT NULL,
  latitude DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  INDEX country (country ASC),
  CONSTRAINT FK_countries
    FOREIGN KEY (country)
    REFERENCES countries (id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);


-- -----------------------------------------------------
-- Table employees
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS employees (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  airplane_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  INDEX airplane_id (airplane_id ASC),
  CONSTRAINT FK_employees
    FOREIGN KEY (airplane_id)
    REFERENCES airplanes (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- -----------------------------------------------------
-- Table routes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS routes (
  id INT UNSIGNED NOT NULL,
  from_airport INT UNSIGNED NOT NULL,
  to_airport INT UNSIGNED NOT NULL,
  departure TIME NOT NULL,
  arrival TIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  INDEX from_airport (from_airport ASC),
  INDEX to_airport (to_airport ASC),
  CONSTRAINT FK1_routes
    FOREIGN KEY (from_airport)
    REFERENCES airports (id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION,
  CONSTRAINT FK2_routes
    FOREIGN KEY (to_airport)
    REFERENCES airports (id)
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);


-- -----------------------------------------------------
-- Table flights
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS flights (
  id INT UNSIGNED NOT NULL,
  route_id INT UNSIGNED NOT NULL,
  airplane_id INT UNSIGNED NOT NULL,
  date_log DATE NOT NULL,
  flight_status ENUM('STANDBY', 'SCHEDULED', 'DELAYED', 'DEPARTED', 'ARRIVED', 'CANCELLED', 'PAST FLIGHT') NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  INDEX route_id (route_id ASC),
  INDEX airplane_id (airplane_id ASC),
  CONSTRAINT FK1_routes_id
    FOREIGN KEY (route_id)
    REFERENCES routes (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK2_airplanes_id
    FOREIGN KEY (airplane_id)
    REFERENCES airplanes (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table reservations
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS reservations (
  id INT UNSIGNED NOT NULL,
  flight_no INT UNSIGNED NOT NULL,
  seat_no VARCHAR(5) NOT NULL,
  price DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (id),
  INDEX flight_no (flight_no ASC),
  UNIQUE INDEX id_UNIQUE (id ASC),
  UNIQUE INDEX seat_no_UNIQUE (seat_no ASC),
  CONSTRAINT FK_reservations
    FOREIGN KEY (flight_no)
    REFERENCES flights (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table licenses
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS licenses (
  id INT UNSIGNED NOT NULL,
  certification_no INT UNSIGNED NOT NULL,
  issued DATE NOT NULL,
  expired DATE NOT NULL,
  UNIQUE INDEX certification_no_UNIQUE (certification_no ASC),
  INDEX fk_licenses_employees1_idx (id ASC),
  PRIMARY KEY (id),
  CONSTRAINT fk_license
    FOREIGN KEY (id)
    REFERENCES employees (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table packages
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS packages (
  id INT UNSIGNED NOT NULL,
  name VARCHAR(45) NOT NULL,
  address VARCHAR(75) NOT NULL,
  airplane_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) ,
  INDEX airplane_id (airplane_id ASC) ,
  CONSTRAINT FK_packages
    FOREIGN KEY (airplane_id)
    REFERENCES airplanes (id)
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table passengers
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS passengers (
  id INT UNSIGNED NOT NULL,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  passport_no INT UNSIGNED NOT NULL,
  confirmation_no INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  INDEX confirmation_no (confirmation_no ASC),
  CONSTRAINT FK_passengers
    FOREIGN KEY (confirmation_no)
    REFERENCES reservations (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);